In [1]:
import numpy as np
np.__version__

'1.26.4'

In [2]:
# From Python list
a = np.array([1, 2, 3, 4, 5])
# 2D array (matrix)
b = np.array([[1, 2, 3],
              [4, 5, 6]])

print("a:", a, "shape:", a.shape, "ndim:", a.ndim)
print("b:\n", b, "\nshape:", b.shape, "ndim:", b.ndim)

# Quick creators
z = np.zeros((2, 3), dtype=np.float32)
o = np.ones((3, 2), dtype=np.int32)
r = np.arange(0, 12, 2)     # 0..10 step 2 → [0 2 4 6 8 10]
lin = np.linspace(0, 1, 5)  # 5 points from 0 to 1

z, o, r, lin


a: [1 2 3 4 5] shape: (5,) ndim: 1
b:
 [[1 2 3]
 [4 5 6]] 
shape: (2, 3) ndim: 2


(array([[0., 0., 0.],
        [0., 0., 0.]], dtype=float32),
 array([[1, 1],
        [1, 1],
        [1, 1]], dtype=int32),
 array([ 0,  2,  4,  6,  8, 10]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]))

In [3]:
m = np.arange(12)        # [0..11]
m2 = m.reshape(3, 4)     # 3 rows, 4 cols
m3 = m.reshape(2, 2, 3)  # 3D

print("m:", m, "shape:", m.shape)
print("m2:\n", m2, "shape:", m2.shape)
print("m3 shape:", m3.shape)

# Flatten & ravel
flat_copy = m2.flatten()   # returns a copy
flat_view = m2.ravel()     # returns a view when possible
(flat_copy.base is None, flat_view.base is not None)

m: [ 0  1  2  3  4  5  6  7  8  9 10 11] shape: (12,)
m2:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] shape: (3, 4)
m3 shape: (2, 2, 3)


(True, True)

In [4]:
x = np.arange(1, 13).reshape(3, 4)
print(x)

# Basic slicing
row0 = x[0, :]        # first row
col1 = x[:, 1]        # second column
block = x[0:2, 1:3]   # rows 0-1, cols 1-2

row0, col1, block


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


(array([1, 2, 3, 4]),
 array([ 2,  6, 10]),
 array([[2, 3],
        [6, 7]]))

In [5]:
y = np.arange(10)
mask = y % 2 == 0     # even numbers
evens = y[mask]
evens


array([0, 2, 4, 6, 8])

In [6]:
M = np.arange(12).reshape(3, 4)
v = np.array([1, 10, 100, 1000])  # shape (4,)
# Add v to each row of M
M_plus_v = M + v
M_plus_v


array([[   1,   11,  102, 1003],
       [   5,   15,  106, 1007],
       [   9,   19,  110, 1011]])

In [7]:
A = np.arange(6).reshape(2, 3)
B = np.arange(100, 106).reshape(2, 3)

vstacked = np.vstack([A, B])      # shape (4,3)
hstacked = np.hstack([A, B])      # shape (2,6)

vstacked, hstacked


(array([[  0,   1,   2],
        [  3,   4,   5],
        [100, 101, 102],
        [103, 104, 105]]),
 array([[  0,   1,   2, 100, 101, 102],
        [  3,   4,   5, 103, 104, 105]]))

In [8]:
# Create compatible shapes
P = np.array([[1, 2, 3],
              [4, 5, 6]])          # (2,3)
Q = np.array([[7,  8],
              [9, 10],
              [11,12]])            # (3,2)

# Matrix multiply: (2,3) @ (3,2) -> (2,2)
PQ = P @ Q               # preferred
PQ_np = np.matmul(P, Q)  # equivalent

PQ, PQ_np, PQ.shape


(array([[ 58,  64],
        [139, 154]]),
 array([[ 58,  64],
        [139, 154]]),
 (2, 2))

In [9]:
# Shape & value sanity checks
assert PQ.shape == (2, 2)
assert np.allclose(PQ, PQ_np)
assert np.array_equal((np.arange(12).reshape(3,4) + np.array([1,10,100,1000])).shape, (3,4))

"Sanity checks passed ✅"


'Sanity checks passed ✅'

In [10]:
np.save("demo_matrix.npy", PQ)     # saves to notebook working dir
"Saved demo_matrix.npy"


'Saved demo_matrix.npy'

In [1]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Vertical stack
v_stack = np.vstack((a, b))
print("Vertical Stack:\n", v_stack)

# Horizontal stack
h_stack = np.hstack((a, b))
print("Horizontal Stack:\n", h_stack)


Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]


In [2]:
arr = np.array([10, 20, 30, 40, 50])

# Extract elements greater than 25
greater_than_25 = arr[arr > 25]
print("Elements > 25:", greater_than_25)

# Replace elements conditionally
arr[arr > 25] = 99
print("Modified Array:", arr)


Elements > 25: [30 40 50]
Modified Array: [10 20 99 99 99]


In [3]:
# Add a 1D array to each row of a 2D array
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

vector = np.array([10, 20, 30])

result = matrix + vector  # vector gets "broadcasted" to each row
print("Broadcasted Addition:\n", result)


Broadcasted Addition:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]
